### ISSUE TITLE
"Big Sur"

### ISSUE THREAD

**Issue by abidshahriar** [QiuChenly/ASUS_FX53VD_ZX53VD_FX86FE_EFI#2]
Hi, Your EFI has been always perfect for my rig.
I really hope and wish that you figure out a way to crack The Big Sur.
Can't wait to see the Big Sur EFi in your git Repository,
Good luck :)  👍

**Comment by QiuChenly** [comment]
Thank you for your approval😃.
We have a test version of OpenCore EFI Package for the "macOS Big Sur Developer Beta 1/2".
But macOS 10.16 have some Bugs(@Apple).
Suggest waiting Apple Release macOS Big Sur Offcial Version for OTA Update this(i means from macOS 10.15 update to macOS 10.16) and at that time we will upload the new OpenCore EFI Package.

if you want to experience the macOS 11 Beta , i can upload the Test OC EFI Package to you.

**Comment by abidshahriar** [comment]
Glad to know that you guys are working on Big Sir ..It's a relief to know that.. would love to experience the macOS 11 beta.
Surely you can upload the test opencore EFI to me, ..I would highly appreciate that. 😊

**Comment by QiuChenly** [comment]
NOT WORKING:

- HD 630 HDMI.

OTHER:
Same as OC - V5, and other Everything OK.

File:
[EFI - OC - V6 - Big Sur Beta Version 1.zip](https://github.com/QiuChenly/ASUS_FX53VD_ZX53VD_FX86FE_EFI/files/4936183/EFI.-.OC.-.V6.-.Big.Sur.Beta.Version.1.zip)

WARNING:
1. BACK UP THE ORIGINAL EFI FILE.
2. Recommended Installation to new partition.
3. Don't directly cover your own 10.15 system.
4. It's just a beta version.

**Comment by abidshahriar** [comment]
Hi,
Getting this panic in Preboot..Installed BigSur beta 3. ![Uploading 88466809...]()

**Comment by QiuChenly** [comment]
this OC just support Beta 1/2....but now have a new OC EFI Package for BigSur Beta 3 version😄,i will upload it later.

**Comment by abidshahriar** [comment]
My machine is GL553VE..Its almost the same with FX553VD or FX553VE...Believe me for my machine i just extra need to disable dgpu and everything works with your efi(earlier). No I haven't try it with Beta 1 or Beta 2...Installed beta3 with adding extra boot-args,
vsmggen=1, -lilubetaall,debug=0x100..

now having this paninc in preboot

![image](https://user-images.githubusercontent.com/64680295/88469104-23c82600-cf0f-11ea-89e6-27f3406c1f73.jpeg)

**Comment by abidshahriar** [comment]
Could you please upload to me the EFI suitable for Beta 3 .. ?

**Comment by abidshahriar** [comment]
this is my working efi ,which I am currently using for Mojave..

. If you want you can check inside.

https://drive.google.com/file/d/1ZuOcQ63kCk2ufP8jdFANU-chR19ht-IQ/view?usp=sharing

**Comment by abidshahriar** [comment]
upload me the beta 3 efi please. i think that would work.

**Comment by abidshahriar** [comment]
Getting random panics ![image](https://user-images.githubusercontent.com/64680295/88475495-26983a80-cf52-11ea-9d5d-78c8d678a273.jpeg)

**Comment by abidshahriar** [comment]
**update: Your EFI is working for me with beta 1**

**Comment by abidshahriar** [comment]
Are we getting a update any soon?

**Comment by QiuChenly** [comment]
sry,i'm so busy for my work....i will upload the new EFI package.

**Comment by abidshahriar** [comment]
@QiuChenly sure...Take time...Hope you upload it soon.
TIA 😃

**Comment by abidshahriar** [comment]
@QiuChenly hello...Hope you are doing well... Any update for BIg Sur Stable EFI?

**Comment by QiuChenly** [comment]
EFI - OC - V9.1 Stable Version  will support macOS 11.2
